# permissions for end users to edit composableoperatorrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: composableoperatorrequest-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - composableoperatorrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - composableoperatorrequests/status
  verbs:
  - get
