
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operand-deployment-lifecycle-manager
rules:
- verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  apiGroups:
    - operator.ibm.com
  resources:
    - operandbindinfos
    - operandconfigs
    - operandregistries
    - operandrequests
    - operandbindinfos/status
    - operandconfigs/status
    - operandregistries/status
    - operandrequests/status
    - operandbindinfos/finalizers
    - operandrequests/finalizers
- apiGroups:
  - operator.ibm.com
  resources:
  - certmanagers
  - ibmlicensings
  - meteringreportservers
  - auditloggings
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - clusterhealth.ibm.com
  resources:
  - clusterservicestatuses
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - certmanager.k8s.io
  resources:
  - clusterissuers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: operand-deployment-lifecycle-manager
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
