apiVersion: operator.ibm.com/v1alpha1
kind: MetaOperatorCatalog
metadata:
  name: common-service
spec:
  operators:
  - name: ibm-metering-operator
    namespace: ibm-metering-operator
    channel: alpha
    packageName: ibm-metering-operator-app
    sourceName: opencloud-operators
    sourceNamespace: openshift-marketplace
    targetNamespaces:
      - ibm-metering-operator
  - name: ibm-licensing-operator
    namespace: ibm-licensing-operator
    channel: alpha
    packageName: ibm-licensing-operator-app
    sourceName: opencloud-operators
    sourceNamespace: openshift-marketplace
    targetNamespaces:
      - ibm-licensing-operator
