apiVersion: operator.ibm.com/v1alpha1
kind: MetaOperatorConfig
metadata:
  name: common-service
spec:
  services:
  - name: ibm-metering-operator
    spec:
      metering: {}
      meteringUI: {}
  - name: ibm-licensing-operator
    spec:
      IBMLicensing: {}
  - name: ibm-mongodb-operator
    spec:
      mongodb: {}
  - name: ibm-cert-manager-operator
    spec:
      certManager: {}
  - name: ibm-healthcheck-operator
    spec:
      healthService: {}
  - name: ibm-management-repo-operator
    spec:
      management-repo: {}
  - name: ibm-helm-repo-operator
    spec:
      helm-repo: {}
  - name: ibm-helm-api-operator
    spec:
      helm-api: {}
