apiVersion: operator.ibm.com/v1alpha1
kind: MetaOperatorSet
metadata:
  name: common-service
spec:
  services:
  - name: ibm-metering-operator
    state: present
    description: The service used to meter workloads in a kubernetes cluster
  - name: etcd
    state: present
  - name: jenkins
    state: present
