apiVersion: operator.ibm.com/v1alpha1
kind: OperandRegistry
metadata:
  name: example-service
spec:
  operators:
  - name: jenkins
    namespace: default
    channel: alpha
    packageName: jenkins-operator
    sourceName: community-operators
    sourceNamespace: openshift-marketplace
