apiVersion: operator.ibm.com/v1alpha1
kind: MetaOperatorSet
metadata:
  name: common-service
spec:
  services:
  - name: etcd
    state: present
  - name: jenkins
    state: present
  - name: ibm-cert-manager-operator
    state: present
    description: Operator for managing deployment of cert-manager service.
