apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operandrequests.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: OperandRequest
    listKind: OperandRequestList
    plural: operandrequests
    shortNames:
    - opreq
    singular: operandrequest
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: OperandRequest is the Schema for the operandrequests API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OperandRequestSpec defines the desired state of OperandRequest
          properties:
            services:
              description: Services defines a list of operator installation states
              items:
                description: SetService is the service configuration for a common
                  service
                properties:
                  channel:
                    type: string
                  name:
                    type: string
                  state:
                    type: string
                required:
                - name
                - state
                type: object
              type: array
          required:
          - services
          type: object
        status:
          description: OperandRequestStatus defines the observed state of OperandRequest
          properties:
            conditions:
              description: Conditions represents the current state of the Set Service
              items:
                description: Condition defines the current state of operator deploy
                properties:
                  lastUpdateTime:
                    type: string
                  message:
                    type: string
                  name:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    description: ConditionType is the condition of a service
                    type: string
                type: object
              type: array
            member:
              description: Members represnets the current operand status of the set
              items:
                description: MemberStatus show if the Operator is ready
                properties:
                  name:
                    description: The member name are the same as the subscription
                      name
                    type: string
                  phase:
                    description: The operand phase include None, Creating, Running,
                      Failed
                    properties:
                      operandPhase:
                        description: ServicePhase defines the service status
                        type: string
                      operatorPhase:
                        description: ClusterServiceVersionPhase is a label for the
                          condition of a ClusterServiceVersion at the current time.
                        type: string
                    type: object
                required:
                - name
                - phase
                type: object
              type: array
            phase:
              description: Phase is the cluster running phase
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
