apiVersion: operator.ibm.com/v1alpha1
kind: MetaOperatorCatalog
metadata:
  name: common-service
spec:
  operators:
  - name: jenkins
    namespace: jenkins-operator
    channel: alpha
    packageName: jenkins-operator
    sourceName: community-operators
    sourceNamespace: openshift-marketplace
    targetNamespaces:
      - jenkins-operator
  - name: etcd
    namespace: etcd-operator
    channel: singlenamespace-alpha
    packageName: etcd
    sourceName: community-operators
    sourceNamespace: openshift-marketplace
    targetNamespaces:
      - etcd-operator
  - name: ibm-cert-manager-operator
    namespace: ibm-cs-certmanager
    channel: alpha
    packageName: ibm-cert-manager-operator
    sourceName: opencloud-operators
    sourceNamespace: openshift-marketplace
    description: Operator for managing deployment of cert-manager service.
