apiVersion: operator.ibm.com/v1alpha1
kind: MetaOperatorSet
metadata:
  name: common-service
spec:
  services:
  - name: ibm-metering-operator
    state: absent
    description: The service used to meter workloads in a kubernetes cluster
  - name: ibm-licensing-operator
    state: present
