apiVersion: operator.ibm.com/v1alpha1
kind: MetaOperatorConfig
metadata:
  name: common-service
spec:
  services:
  - name: jenkins
    spec:
      jenkins:
        service:
          port: 8081
  - name: etcd
    spec:
      etcdCluster:
        size: 1
  - name: ibm-cert-manager-operator
    spec:
      enableWebhook: true
      imageRegistry: quay.io/opencloudio
      pullSecret:
        name: pull-secret-1
