apiVersion: operator.ibm.com/v1alpha1
kind: MetaOperatorConfig
metadata:
  name: common-service
spec:
  services:
  - name: ibm-metering-operator
    spec:
      Metering:
        iamNamespace: kube-system
        mongodb:
          host: mongodb.kube-system.svc.cluster.local
      MeteringUI:
        iamNamespace: kube-system
        mongodb:
          host: mongodb.kube-system.svc.cluster.local
  - name: jenkins
    spec:
      jenkins:
        service:
          port: 8081
  - name: etcd
    spec:
      etcdCluster:
        size: 1
