apiVersion: operator.ibm.com/v1alpha1
kind: OperandConfig
metadata:
  labels:
    app.kubernetes.io/instance: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/managed-by: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/name: "odlm"
  name: example-service
spec:
  services:
  - name: etcd
    spec:
      etcdCluster:
        size: 1
  - name: jenkins
    spec:
      jenkins:
        service:
          port: 8081
