channels:
- currentCSV: operand-deployment-lifecycle-manager.v1.2.3
  name: beta
- currentCSV: operand-deployment-lifecycle-manager.v1.2.4
  name: dev
- currentCSV: operand-deployment-lifecycle-manager.v1.2.3
  name: stable-v1
defaultChannel: stable-v1
packageName: operand-deployment-lifecycle-manager-app
