apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: meta-operator
  template:
    metadata:
      labels:
        name: meta-operator
    spec:
      serviceAccount: meta-operator
      containers:
        - name: meta-operator
          # Replace this with the built image name
          image: quay.io/opencloudio/meta-operator
          command:
          - meta-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "meta-operator"
