apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/managed-by: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/name: "odlm"
  name: operand-deployment-lifecycle-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operand-deployment-lifecycle-manager
  template:
    metadata:
      labels:
        name: operand-deployment-lifecycle-manager
        app.kubernetes.io/instance: operand-deployment-lifecycle-manager
        app.kubernetes.io/managed-by: "operand-deployment-lifecycle-manager"
        app.kubernetes.io/name: "odlm"
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.4.0"
        productMetric: "FREE"
    spec:
      serviceAccountName: operand-deployment-lifecycle-manager
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: operand-deployment-lifecycle-manager
          # Replace this with the built image name
          image: quay.io/opencloudio/odlm@sha256:06660c203ff5e0f82dfbf7ab990b3a2c0229cdff5e06085ddc44e3c71bf4b713
          command:
          - odlm
          args:
          - "-v=2"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "operand-deployment-lifecycle-manager"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
