apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/managed-by: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/name: "odlm"
  name: operand-deployment-lifecycle-manager
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
