kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operand-deployment-lifecycle-manager
subjects:
- kind: ServiceAccount
  name: operand-deployment-lifecycle-manager
  namespace: scorecard
roleRef:
  kind: ClusterRole
  name: operand-deployment-lifecycle-manager
  apiGroup: rbac.authorization.k8s.io
