kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/instance: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/managed-by: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/name: "odlm"
  name: operand-deployment-lifecycle-manager
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: operand-deployment-lifecycle-manager
  apiGroup: rbac.authorization.k8s.io
