kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operand-deployment-lifecycle-manager
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: operand-deployment-lifecycle-manager
  apiGroup: rbac.authorization.k8s.io
