apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/managed-by: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/name: "odlm"
  name: operandrequests.operator.ibm.com
