apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: commonservicesets.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: CommonServiceSet
    listKind: CommonServiceSetList
    plural: commonservicesets
    shortNames:
    - css
    singular: commonserviceset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CommonServiceSet is the Schema for the commonservicesets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CommonServiceSetSpec defines the desired state of CommonServiceSet
          properties:
            services:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  channel:
                    type: string
                  description:
                    type: string
                  name:
                    type: string
                  state:
                    type: string
                required:
                - name
                - state
                type: object
              type: array
          required:
          - services
          type: object
        status:
          description: CommonServiceSetStatus defines the observed state of CommonServiceSet
          properties:
            states:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                States represents the current state of the MetaOperator'
              items:
                description: OperatorState defines the current state of operator deploy
                properties:
                  lastUpdateTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  name:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
