apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operandrequests.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: OperandRequest
    listKind: OperandRequestList
    plural: operandrequests
    shortNames:
    - opreq
    singular: operandrequest
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: OperandRequest is the Schema for the operandrequests API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: The OperandRequestSpec identifies one or more specific operands
            (from a specific Registry) that should actually be installed
          properties:
            requests:
              description: Requests defines a list of operands installation
              items:
                description: Request identifies a operand detail
                properties:
                  description:
                    description: Description is an optional description for the request
                    type: string
                  operands:
                    description: Operands deines a list of the OperandRegistry entry
                      for the operand to be deployed
                    items:
                      description: Operand defines the name and binding information
                        for one operator
                      properties:
                        bindings:
                          description: Specify a Binding list
                          items:
                            description: Binding defines the scope of the operand,
                              and the resources, like Secret, ConfigMap and ServiceAccount
                            properties:
                              configMap:
                                description: Specifies the name of a configmap that
                                  should contain information shared from the deployed
                                  operand if it shares configmaps with requesters.
                                type: string
                              scope:
                                description: 'A scope indicator, either public or
                                  private Valid values are: - "private" (default):
                                  deployment only request from the containing names;
                                  - "public": deployment can be requested from other
                                  namespaces;'
                                enum:
                                - public
                                - private
                                type: string
                              secret:
                                description: Specifies that name of a secret that
                                  should contain information shared from the deployed
                                  operand if it shares secrets with requesters.
                                type: string
                              serviceAccount:
                                description: Specifies the name of the service account
                                  that needs to access the created secret and/or configmap
                                  (e.g. the service account being used by running
                                  pods), so that ODLM can sure that the access rights
                                  are set correctly, if needed.
                                type: string
                            type: object
                          type: array
                        name:
                          description: Name of the operand to be deployed
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                  registry:
                    description: Specifies the name in which the OperandRegistry reside.
                    type: string
                  registryNamespace:
                    description: Specifies the namespace in which the OperandRegistry
                      reside. The default is the current namespace in which the request
                      is defined.
                    type: string
                required:
                - operands
                - registry
                type: object
              type: array
          required:
          - requests
          type: object
        status:
          description: OperandRequestStatus defines the observed state of OperandRequest
          properties:
            conditions:
              description: Conditions represents the current state of the Request
                Service
              items:
                description: Condition represents the current state of the Request
                  Service A condition might not show up if it is not happening
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition
                    type: string
                  reason:
                    description: The reason for the condition's last transition
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown
                    type: string
                  type:
                    description: Type of condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            members:
              description: Members represnets the current operand status of the set
              items:
                description: MemberStatus show if the Operator is ready
                properties:
                  name:
                    description: The member name are the same as the subscription
                      name
                    type: string
                  phase:
                    description: The operand phase include None, Creating, Running,
                      Failed
                    properties:
                      operandPhase:
                        description: OperandPhase show the deploy phase of the operator
                          instance
                        type: string
                      operatorPhase:
                        description: OperatorPhase show the deploy phase of the operator
                        type: string
                    type: object
                required:
                - name
                type: object
              type: array
            phase:
              description: Phase is the cluster running phase
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
