apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: metaoperatorconfigs.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: MetaOperatorConfig
    listKind: MetaOperatorConfigList
    plural: metaoperatorconfigs
    shortNames:
    - mocon
    singular: metaoperatorconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MetaOperatorConfig is the Schema for the metaoperatorconfigs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MetaOperatorConfigSpec defines the desired state of MetaOperatorConfig
          properties:
            services:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                Services is a list of configuration of service'
              items:
                description: ConfigService defines the configuration of the service
                properties:
                  name:
                    description: Name is the subscription name
                    type: string
                  spec:
                    additionalProperties:
                      type: object
                    description: Spec is the map of configuration of custome service
                    type: object
                  state:
                    description: State is a flag to enable or disable service
                    type: string
                required:
                - name
                - spec
                type: object
              type: array
          type: object
        status:
          description: MetaOperatorConfigStatus defines the observed state of MetaOperatorConfig
          properties:
            serviceStatus:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                ServiceStatus defines all the status of a operator'
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
